<a href="https://colab.research.google.com/github/CHHyuk/Practice/blob/main/01_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import numpy as np
# ndArray

# 1차원 ndArray 생성
np.array([1,2,3,4])
arr1 = np.array([1,2,3,4]) # 넘파이 ndArray
arr2 = [1,2,3,4] # 파이썬 리스트

print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'list'>


In [99]:
# 2차원 ndArray 생성
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8]])
print('2차원 배열 arr2')
print(arr2)

# 3차원 nbArray 생성
arr3 = np.array([[[1.0,2.0,3,4],[5,6,7,8]],
                  [[1,2,3,4],[5,6,7,8]]])
print('3차원 배열 arr3')
print(arr3)

2차원 배열 arr2
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열 arr3
[[[1. 2. 3. 4.]
  [5. 6. 7. 8.]]

 [[1. 2. 3. 4.]
  [5. 6. 7. 8.]]]


In [100]:
# ndarray.ndim
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# ndarray.shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# ndarray.size
print(arr1.size)
print(arr2.size)
print(arr3.size)

# ndarray.dtype
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

1
2
3
(4,)
(2, 4)
(2, 2, 4)
4
8
16
int64
int64
float64


In [101]:
# 배열 생성 함수
# 0으로 채워진 행렬
arr_0 = np.zeros((3,4))
print(arr_0, type(arr_0))

# 1로 채워진 행렬
arr_1 = np.ones((2,3,4))
print(arr_1)

# i로 채워진 행렬
arr_i = np.full((4,4),3) # 4x4 행렬을 3으로 채워준다
print(arr_i)

# like > 다른 배열의 모양을 본따서
print(np.zeros_like(arr2))
print(np.ones_like(arr2))
print(np.full_like(arr2,3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] <class 'numpy.ndarray'>
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
[[0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]]
[[3 3 3 3]
 [3 3 3 3]]


In [102]:
# random > 난수 발생
np.random.seed(1) # 최초 난수 생성 기준

# -100 ~ 100 사이의 정수로 3 x 3 행렬 생성
np.random.randint(-100,100,(3,3))

# 0 ~ 10 사이의 정수로 2 x 2 x 3 행렬 생성
np.random.randint(0,10,(2,2,3))

array([[[7, 6, 9],
        [2, 4, 5]],

       [[2, 4, 2],
        [4, 7, 7]]])

In [103]:
# 인덱싱
li = [1,2,3,4]
li[0] # 원하는 요소에 접근하는 방식

# 1차원 배열의 인덱싱
arr1[0] # 한개에 접근

# 1차원 슬라이싱
# arr1 = np.array([1,2,3,4])
arr1[1:3:1] # [시작, 끝, 보폭]

# 2차원 배열의 인덱싱
# arr2 = np.array([[1,2,3,4],
#                 [5,6,7,8]])
print(arr2[0,1])
print(arr2[1,2])

# 2차원 슬라이싱
arr2[1:2:,1:3:]

# fancy 인덱싱
# 원하는 인덱스를 배열로 넘겨주는 인덱싱
# 1차원
arr1[[0,1,3]]

# 2차원
arr2[[0,1],[1,3]]
arr2[::,[0,3]]

# 논리값 인덱싱
arr1[[True, False, True, False]]
arr1[arr1 > 2]

2
7


array([3, 4])

In [106]:
# -10 ~10 사이의 정수로 (3,4) 모양의 배열을 만들고 arr1에 저장
arr1 = np.random.randint(-10,10,(3,4))
print(arr1)
# 아래와 같은 2차원 배열을 만들고 arr2에 저장
# 1,2,3,4
# 5,6,7,8
# 9,10,11,12
# 13,14,15,16
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
print(arr2)

# 1. 각 배열의 차원, 모양, 원소의 갯수를 확인
print('arr1의 차원, 모양, 원소개수')
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print('arr2의 차원, 모양, 원소개수')
print(arr2.ndim)
print(arr2.shape)
print(arr3.size)
# 2. arr1에서 행은 모두 출력하고 열은 첫번째, 세번째만 출력
print(arr1[::,[0,2]])

# 3. arr2에서 아래처럼 나오게 인덱싱해주세요
# [6, 7]
# [10, 11]
print(arr2[1:3,1:3])

[[  2   6   3   9]
 [ -1   8   5 -10]
 [ -6   5  -8  -3]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
arr1의 차원, 모양, 원소개수
2
(3, 4)
12
arr2의 차원, 모양, 원소개수
2
(4, 4)
16
[[ 2  3]
 [-1  5]
 [-6 -8]]
[[ 6  7]
 [10 11]]
